### ISSUE TITLE
Covid-19 Updates (India) [Template Submission]

### ISSUE THREAD

**Issue by jamesshah** [twilio-labs/code-exchange#10]
**What's the programming language?**

> Back-end: Node.js & Express Framework
> Database : MongoDB

**Template GitHub URL:**
https://github.com/jamesshah/Covid19-Updates

**Author Information (please fill out):**

- Author name : James Shah
- Author GitHub organization/user: github.com/jamesshah
- GitHub username you used to sign [the Agreement](https://ahoy.twilio.com/code-exchange-community):  jamesshah

**Additional dependencies:**
They are listed at the project's README.

**Checklist:**

- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

Please give me feedback, in case i did something not properly (It's my first issue on github as well!)

**Comment by dkundel** [comment]
Thank you for submitting your template @jamesshah! We are working on adding your template. I'll post here once it's live. **But please note that this is _not_ a valid submission for the DEV hackathon. For this you'll have to post on DEV using https://dev.to/new/twiliohackathon as a template**

**Comment by jamesshah** [comment]
@dkundel Thanks for the heads up!!😅

**Comment by dkundel** [comment]
Sorry for the delay but your submission is live :) https://www.twilio.com/code-exchange/subscribing-sms-updates
