### ISSUE TITLE
Django REST API with JWT Authentication protected by Twilio Two-factor Authentication

### ISSUE THREAD

**Issue by grillazz** [twilio-labs/code-exchange#12]
**What's the use case for the template?**
In these days we need to be sure that data which we using and sharing is consistent and we can trust in it. One of methods is protect your api as best as possible. I decided to share my approach to protect Django REST Framework JWT with Twilio 2FA. Hope it will save time which i spent to implement Twilio 2FA for REST API safely. In this sample project i showing integration with Verify API and Authy API from Twilio for Python.

**What's the programming language?**
Python and Django

**Template GitHub URL:**
https://github.com/grillazz/twofa_for_drf

**Author Information (please fill out):**

- Author name : Jakub Miazek
- Author GitHub organization/user: https://github.com/grillazz
- GitHub username you used to sign the Agreement: grillazz

**Checklist:**

- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

**Comment by dkundel** [comment]
Thank you for submitting your template @grillazz! We are working on adding your template. I'll post here once it's live. 

But please note that this is not a valid submission for the [DEV hackathon](https://twil.io/dev-hack-april) in case you were intending to submit for that as well. For this you'll have to post on DEV using https://dev.to/new/twiliohackathon as a template

**Comment by grillazz** [comment]
Thanks @dkundel 
I think i alredy added my submission to DEV here https://dev.to/grillazz/strengthen-protection-of-django-drf-and-jwt-with-twilio-authy-2fa-1b4n

**Comment by dkundel** [comment]
Hi @grillazz! I've added your submission to CodeExchange. There were two things we noticed when looking through your submission:
1) the README mentions that the app uses the Verify API but it doesn't appear to use it anywhere. There's also a grammar mistake in that sentence
2) There's a part in the README where you say "Instructions you can find here" that should say "You can find the instructions here" but it's also missing a link.

**Comment by dkundel** [comment]
Here's your app though: https://www.twilio.com/code-exchange/django-rest-api-protection-2fa

**Comment by grillazz** [comment]
> Hi @grillazz! I've added your submission to CodeExchange. There were two things we noticed when looking through your submission:
> 
> 1. the README mentions that the app uses the Verify API but it doesn't appear to use it anywhere. There's also a grammar mistake in that sentence
> 2. There's a part in the README where you say "Instructions you can find here" that should say "You can find the instructions here" but it's also missing a link.

Thanks. README Updated with you suggestions above.
