### ISSUE TITLE
[Template Submission]

### ISSUE THREAD

**Issue by joro550** [twilio-labs/code-exchange#14]
This is a request in regards to the dev.to hackathon, here is my blog post url - https://dev.to/joro550/placeholder-title-414l

**What's the use case for the template?**
---
Right now the world has it's mind on COVID-19 how can you help? But looking beyond and forward how do we help the homeless the starving, how do we fix global warming. This project is to help people who want to help with all of these causes and more, oganizations can create events that they are currently running i.e. Donate to fix a curch roof, and have a quick "call to action" that people can use to donate to help that event.

Updates can be published to events to share how progress is coming along so that people are informed with how their contribution helped with the cause.

----

**What's the programming language?**
C# backend
C# (webassembly/Blazor) frontend

**Template GitHub URL:**
https://github.com/joro550/Artemis

**Author Information:**

- Author name (or organization if submitted on behalf of a company): Mark Davies
- Author GitHub organization/user: Mark Davies
- GitHub username you used to sign [the Agreement](https://ahoy.twilio.com/code-exchange-community): joro550

**Additional dependencies:**
Sql Server (for database)

**Checklist:**
- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

**Comment by dkundel** [comment]
Thank you @joro550! Please make sure you update your DEV.to post in time for the hackathon submission deadline. Anything submitted through DEV.to as part of the hackathon will automatically be considered to also be added to CodeExchange.
I'll close this issue in the meantime. Feel free to re-open it when you finished your submission or want to submit an application for CodeExchange outside of the framework of the hackathon.
