### ISSUE TITLE
Typeform Handler - Extract phone number and call user

### ISSUE THREAD

**Issue by picsoung** [twilio-labs/code-exchange#21]
Hey @dkundel 

Let me know what you think and if there is something to change ;)

Thanks

**What's the use case for the template?**
Demonstrating how to extract data from a Typeform webhook and act on it. In this case placing a call to a phone number provided by a user in a typeform.

**What's the programming language?**
NodeJS with Express

**Template GitHub URL:**
https://github.com/picsoung/tf-twilio

**Author Information (please fill out):**

- Author name (or organization if submitted on behalf of a company): [Nicolas Grenié]
- Author GitHub organization/user: [github.com/picsoung]
- GitHub username you used to sign [the Agreement](https://ahoy.twilio.com/code-exchange-community):  [picsoung]

**Additional dependencies:**
Axios and crypto

**Checklist:**

> Please check every part of this checklist for us to process your request. You can do this by marking them with `[x]` instead of `[ ]`.

- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

**Comment by dkundel** [comment]
Hi @picsoung. Great submission. Could you make sure it contains a LICENSE file though indicating under which license the code is?

Thank you!

**Comment by dkundel** [comment]
Hey @picsoung this is still missing a license file atm :(

**Comment by picsoung** [comment]
Thanks for the reminder @dkundel  ;)
What about now? 😄 

btw it's an example using express, is that an issue?

**Comment by dkundel** [comment]
Perfect. No Express is no issue :) Everything is welcome. I handed your submission over to the team uploading the submissions. Might be a couple of days (i'll be out on vacation) but I'll close this issue in the meantime.

**Comment by picsoung** [comment]
Hey :)
I was revisiting this PR because I realized the example never made it to https://www.twilio.com/code-exchange

let me know if I need to change anything.
Best
