### ISSUE TITLE
Covid-19 Reports [Template Submission]

### ISSUE THREAD

**Issue by AsaoluElijah** [twilio-labs/code-exchange#25]
# Covid-19 Reports
Get covid-19 information as SMS even when you're offline and also help you perform self test right on your mobile device.
**What's the programming language?**
- HTML, CSS, JavaScript & Framework 7 - Front End
- PHP & MySQL - Backend

**Template GitHub URL:**
https://github.com/InventorsDev/covid-hack

**Author Information**

- Organization:  Inventors Dev
- Author GitHub organization/user: https://github.com/InventorsDev
- GitHub username you used to sign : https://github.com/AsaoluElijah

**Comment by dkundel** [comment]
## This submission is not a hackathon submission
Thank you for your submission! Just a reminder that if you are intending to submit to the hackathon, you have to do this *separately* to this submission by creating a post on dev.to/new/twiliohackathon

**Comment by AsaoluElijah** [comment]
Yeah, I've done that also.
I thought this was necessary also
