### ISSUE TITLE
[Template Submission] twilio-dev-container

### ISSUE THREAD

**Issue by shelbyz-prft** [twilio-labs/code-exchange#32]
**Important**:
Please make sure to first read and sign the agreement at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community) before proceeding here.

**IMPORTANT HACKATHON INFO**:
If you are filling this out because you want to submit to the ongoing hackathon with DEV.to, please make sure you post on dev.to using this template: https://dev.to/new/twiliohackathon. Creating an issue in this project is independent of the hackathon and does not automatically qualify you for the hackathon.

**What's the use case for the template?**
Reusable Developer Container for Twilio focusing on using the Serverless Toolkit.  Provides guidance on what data within Twilio to capture for configuration to get up and running quickly in a reusable fashion.  Environment also provides hooks to attach VS Code debugger to running JS or Python.

**What's the programming language?**
Mostly JS / some Python

**Template GitHub URL:**
https://github.com/Perficient-CES/twilio-dev-container

**Author Information (please fill out):**

- Author name (or organization if submitted on behalf of a company): Perficient
- Author GitHub organization/user: https://github.com/orgs/Perficient-CES/teams/twilio
- GitHub username you used to sign [the Agreement](https://ahoy.twilio.com/code-exchange-community): shelbyz-prft

**Additional dependencies:**
Host machine should be able to install/run docker and the user should have access to a Twilio project.  Optionally, use VS Code for additional debugging benefits.

**Checklist:**

> Please check every part of this checklist for us to process your request. You can do this by marking them with `[x]` instead of `[ ]`.

- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

**Comment by dkundel** [comment]
Thanks for your submission @shelbyz-prft! Your submission has been added :)
