### ISSUE TITLE
[Template Submission] Stripe Checkout remember me with Twilio Verify

### ISSUE THREAD

**Issue by thorsten-stripe** [twilio-labs/code-exchange#5]
**What's the use case for the template?**
Use Stripe Checkout to collect payment details for future payments and Twilio Verify to authenticate the customer via SMS code and charge their stored card.

**What's the programming language?**
- Frontend
  - Vanilla JavaScript + HTML + CSS
- Backend (2 servers)
  - JavaScript (Node with Express)
  - Python (with Flask)

**Template GitHub URL:**
https://github.com/stripe-samples/checkout-remember-me-with-twilio-verify
Demo: https://ldmsw.sse.codesandbox.io/

**Author Information (please fill out):**

- Author name (or organization if submitted on behalf of a company): Stripe
- Author GitHub organization/user: https://github.com/stripe-samples
- GitHub username you used to sign [the Agreement](https://ahoy.twilio.com/code-exchange-community): thorsten-stripe

**Additional dependencies:**
- Frontend
  - [intl-tes-input](https://github.com/jackocnr/intl-tel-input): for client-side phone number validation (loaded from CDN)
  - Stripe.js (loaded from https://js.stripe.com/v3/)
- Backend
  - Stripe
  - Twilio
  - Express
  - Flask
  - Dotenv

**Checklist:**

> Please check every part of this checklist for us to process your request. You can do this by marking them with `[x]` instead of `[ ]`.

- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2: https://github.com/stripe-samples/checkout-remember-me-with-twilio-verify/blob/master/LICENSE
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

**Comment by dkundel** [comment]
Thank you @thorsten-stripe for your contribution. We published your templates to CodeExchange :) https://www.twilio.com/code-exchange/fast-checkout-sms-verification
