### ISSUE TITLE
[Template Submission]

### ISSUE THREAD

**Issue by sophi-li** [twilio-labs/code-exchange#6]
**Important**:
Please make sure to first read and sign the agreement at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community) before proceeding here.

**What's the use case for the template?**
This template helps users send text message reminders to themselves. Specifically, this template was used to send a daily text message reminder to user to feed their sourdough starter. A full tutorial and more on what sourdough starter can be found in my blog post, [So You Forgot to Feed Your Sourdough Starter Baby? 🍞👶](https://dev.to/sophia_wyl/so-you-forgot-to-feed-your-sourdough-starter-baby-1g8c)

**What's the programming language?**
JavaScript/Node.js

> For any Twilio Function templates please submit them via a pull request to github.com/twilio-labs/function-templates
N/A

**Template GitHub URL:**
https://github.com/sophi-li/sourdough-timer

**Author Information (please fill out):**

- Author name (or organization if submitted on behalf of a company): None
- Author GitHub organization/user:https://github.com/sophi-li
- GitHub username you used to sign [the Agreement](https://ahoy.twilio.com/code-exchange-community): sophi-li

**Additional dependencies:**
Azure Timer Function

**Checklist:**

> Please check every part of this checklist for us to process your request. You can do this by marking them with `[x]` instead of `[ ]`.

- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

**Comment by dkundel** [comment]
Sorry for the delay @sophi-li but congratulations you are now on the Twilio CodeExchange and you are the first community member to be published there 🎉 
https://www.twilio.com/code-exchange/automatic-sms-reminders
