### ISSUE TITLE
verify-v2-quickstart-python broken for call verify

### ISSUE THREAD

**Issue by nickfun** [twilio-labs/code-exchange#8]
**Where has this bug occurred?**
verify-v2-quickstart-python has a bug. here is a fix: https://github.com/TwilioDevEd/verify-v2-quickstart-python/pull/5

**Describe the bug**
the app uses Twilio Verify, but when you pick to do a voice call instead of SMS it does not make a call.

**To Reproduce**

1. setup the project
2. do the new user flow
3. on the verify step, do not choose the text message option
4. the page will load an error about incorrect "channel"

**Expected behavior**
instead of an error it should make the verification phone call and let the user type in the OTP.

**Screenshots**
n/a

**Template bug info (please complete the following information if the bug exists in one of the templates):**
 - Template source link: https://github.com/TwilioDevEd/verify-v2-quickstart-python
 - OS: mac 10.12.6
 - Programming language and version: python 3.6

**Desktop (please complete the following information):**
same as above, any browser

**Smartphone (please complete the following information):**
n/a

**Additional context**
please see https://github.com/TwilioDevEd/verify-v2-quickstart-python/pull/5

**Comment by dkundel** [comment]
Thank you for flagging and creating the PR @nickfun :) the PR has been merged.
