### ISSUE TITLE
Ding! It's time to work

### ISSUE THREAD

**Issue by alator21** [twilio-labs/code-exchange#9]
**What's the programming language?**
The programming language is typescript and the environment is Node.js

Github URL:
https://github.com/alator21/Ding-time-to-work

- Author name (or organization if submitted on behalf of a company):Rafael Triantafillidis
- Author GitHub organization/user: https://github.com/alator21
- GitHub username you used to sign [the Agreement](https://ahoy.twilio.com/code-exchange-community): alator21

**Additional dependencies:**
They are listed at the project's README

**Checklist:**

- [x] I've filled out the form at [ahoy.twilio.com/code-exchange-community](https://ahoy.twilio.com/code-exchange-community)
- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Twilio's [best practices coding guidelines](https://github.com/twilio-labs/code-exchange/tree/master/guidelines) for my project
- [x] I agree and adhere to the [Code of Conduct](https://github.com/twilio-labs/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The template has been authored by me / or my organization and will be kept up-to-date. If the template will not longer be maintained, I'll notify this project.

Additionaly this is the linked post in the dev.to. [post](https://dev.to/alator21/no-time-to-sleep-ding-it-s-time-to-work-8p7)

question:In the form([ahoy.twilio.com/code-exchange-community) i filled the github handle form with the link to my github profile. Is that valid? Should i have typed something else?
Thanks

Please give me feedback, in case i did something not properly.

**Comment by dkundel** [comment]
Thank you for your submission @alator21. Yes putting the profile URL in is valid :) We'll review your submission soon. Note that this review is unrelated to the hackathon going on at dev.to as those are two separate submissions :)

**Comment by dkundel** [comment]
Hey @alator21! I've published your project on CodeExchange: https://www.twilio.com/code-exchange/daily-scheduled-sms-reminders-typescript

**Comment by dkundel** [comment]
Thank you for contributing :)
